[build]
  command = ""  # build yo'q, oddiy HTML bo'lsa
  publish = "client"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[context.production.environment]
  NODE_ENV = "production"
