name: Deploy to Ubuntu server with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSHPRIVATE_KEY }}

    - name: Pull latest code & restart app on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          
          cd ${{ secrets.DEPLOY_PATH_ONLINECOURSE }}
          git pull origin main
      
          cd ${{ secrets.DEPLOY_PATH_SERVER }}
          npm i
          pm2 restart OnlineCourseServer || pm2 start main.js --name OnlineCourseServer

          cd ${{ secrets.DEPLOY_PATH_CLIENT_CLIENT }}
          npm i
          pm2 restart clientOnlineCourse || pm2 start "npm run start"
        EOF